package wex:runtime;

world messaging-guest {
    export wasi:messaging/incoming-handler@0.2.0-draft;
}

world imports {
    include wasi:keyvalue/imports@0.2.0-draft;
    include wasi:messaging/imports-request-reply@0.2.0-draft;
}
